// Generated by Assets/Hananoki/ManifestJsonUtility/Localize/ja-JP.csv
namespace Hananoki.ManifestJsonUtility {
	public static class L {
		public static string Tr( string s ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), s );
		}
		public static string[] Tr( string[] ss ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), ss );
		}
	}
	public static class S {
		public static string _LocalPackagePaths => L.Tr( "Local Package Paths" );
		public static string _Installablepackages => L.Tr( "Installable packages" );
	}
}
